add tutorials #6
gesistsa/usemh pull request #10
Opened 2024-11-04 21:12 UTC by schochastics

2024-11-04 21:14 UTC, schochastics commented
I am not that happy yet but here is a first idea:

-`use_mh_tutorial_template()` to create a new empty tutorial
-`use_mh_tutorial_utils()` to add all necessary files beyond qmd

2024-11-04 21:48 UTC, chainsawriot commented on inst/templates/tutorial.qmd
> +csl: apa.csl
how about also copy apa.csl and bib.bib?

2024-11-05 09:34 UTC, schochastics commented
@chainsawriot I think it is done now. Done as in: "It works on my machine"

2024-11-05 09:44 UTC, chainsawriot requested changes

2024-11-05 09:44 UTC, chainsawriot commented on R/usemh_tutorial.R
> +        dir <- paste0(active_dir, "/", gsub(" ", "_", title))
Using paste0 to create file path might create issues for our windows-using friends. Please use `file.path()`.

2024-11-05 09:44 UTC, chainsawriot commented on inst/templates/tutorial.qmd
> +This method has been used in previous studies to evaluate ... [e.g. @mueller:2023:DRN].
if `references.bib` is empty, maybe it's better to remove the citation. Or replace it with a "neutral" one. I don't know, perhaps Einstein and put it in `.bib`. It would be better when the template can be immediately rendered.

2024-11-05 10:48 UTC, schochastics commented on inst/templates/tutorial.qmd
> +This method has been used in previous studies to evaluate ... [e.g. @mueller:2023:DRN].
I added your reference back in. I think thats ok

2024-11-05 10:48 UTC, schochastics commented on R/usemh_tutorial.R
> +        dir <- paste0(active_dir, "/", gsub(" ", "_", title))
good catch. It is fixed now

2024-11-05 11:09 UTC, chainsawriot approved these changes

2024-11-05 11:45 UTC, merged